[package]
name = "rust_voronoi"
version = "0.1.0"
authors = ["Yolan Uyttenhove <yolan.uyttenhove@ugent.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
